###GET all movies
GET http://localhost:1234/movies

###GET movie by id
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

###GET movies by genre
GET http://localhost:1234/movies?genre=horror

###POST movie
POST http://localhost:1234/movies
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "ASD ASD ASD",
  "year": 2008,
  "director": "Christopher Nolan",
  "duration": 152,
  "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
  "genre": [
    "Action",
    "Crime",
    "Drama"
  ]
}

###PATCH movie
PATCH http://localhost:1234/movies/cca98941-8d3f-448a-a0f8-8a35748eaf69
Content-Type: application/json

{
  "year": 2023
}